// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/user.proto
// Protobuf C++ Version: 7.36.2

#include "proto/user.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::protobridge::UserInfo
        {&::_pbi::kDescriptorMethods, &::descriptor_table_proto_2fuser_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace protobridge {
class UserInfo::_Internal {
 public:
  using HasBits = decltype(::std::declval<UserInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UserInfo, _impl_._has_bits_);
};

constexpr UserInfo::ParseTableT_ UserInfo::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(UserInfo, _impl_._has_bits_),
      0, // no _extensions_
      7, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967168,  // skipmap
      offsetof(ParseTableT_, field_entries),
      7,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::MpUnknownFields,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::protobridge::UserInfo>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // uint64 id = 1;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserInfo, _impl_.id_), 3>(),
       {8, 3, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.id_)}},
      // string username = 2;
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.username_)}},
      // string email = 3;
      {::_pbi::TcParser::FastUS1,
       {26, 2, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.email_)}},
      // int32 age = 4;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserInfo, _impl_.age_), 4>(),
       {32, 4, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.age_)}},
      // bool is_active = 5;
      {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserInfo, _impl_.is_active_), 5>(),
       {40, 5, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.is_active_)}},
      // int64 created_at_unix = 6;
      {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserInfo, _impl_.created_at_unix_), 6>(),
       {48, 6, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.created_at_unix_)}},
      // repeated string roles = 7;
      {::_pbi::TcParser::FastUR1,
       {58, 0, 0,
        PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.roles_)}},
    }}, {{
      65535, 65535
    }}, {{
      // uint64 id = 1;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
      // string username = 2;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.username_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string email = 3;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.email_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // int32 age = 4;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.age_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // bool is_active = 5;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.is_active_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
      // int64 created_at_unix = 6;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.created_at_unix_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // repeated string roles = 7;
      {PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.roles_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    }},
    // no aux_entries
    {{
      "\24\0\10\5\0\0\0\5"
      "protobridge.UserInfo"
      "username"
      "email"
      "roles"
    }},
  };
}


inline constexpr UserInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : roles_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::protobridge::UserInfo,
            PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.roles_)>()
         }
        ,
        username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        email_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::uint64_t{0u}},
        age_{0},
        is_active_{false},
        created_at_unix_{::int64_t{0}} {}

template <typename>
constexpr UserInfo::UserInfo(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL UserInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UserInfo(arena);
}
constexpr auto UserInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UserInfo), alignof(UserInfo));
}
constexpr auto UserInfo::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &UserInfo::MergeImpl,
          Super_::GetNewImpl<UserInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UserInfo::SharedDtor,
          Super_::GetClearImpl<UserInfo>(), &UserInfo::ByteSizeLong,
              &UserInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UserInfo, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_proto_2fuser_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct UserInfoGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr UserInfoGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 UserInfo_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(UserInfo::InternalGenerateClassData_(
            _default, &UserInfo_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<UserInfo>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~UserInfoGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) UserInfo _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<UserInfo>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(UserInfoGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST UserInfoGlobalsTypeInternal UserInfo_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* UserInfo_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return UserInfo_globals_.GetClassData();
#else
  return UserInfo_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace protobridge
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2fuser_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fuser_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fuser_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.email_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.age_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.is_active_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.created_at_unix_),
        PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.roles_),
        3,
        1,
        2,
        4,
        5,
        6,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::protobridge::UserInfo)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::protobridge::UserInfo_globals_,
};
const char descriptor_table_protodef_proto_2fuser_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020proto/user.proto\022\013protobridge\"\177\n\010UserI"
    "nfo\022\n\n\002id\030\001 \001(\004\022\020\n\010username\030\002 \001(\t\022\r\n\005ema"
    "il\030\003 \001(\t\022\013\n\003age\030\004 \001(\005\022\021\n\tis_active\030\005 \001(\010"
    "\022\027\n\017created_at_unix\030\006 \001(\003\022\r\n\005roles\030\007 \003(\t"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fuser_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fuser_2eproto = {
    false,
    false,
    168,
    descriptor_table_protodef_proto_2fuser_2eproto,
    "proto/user.proto",
    &descriptor_table_proto_2fuser_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_message_globals,
    TableStruct_proto_2fuser_2eproto::offsets,
    file_level_enum_descriptors_proto_2fuser_2eproto,
    file_level_service_descriptors_proto_2fuser_2eproto,
};
namespace protobridge {
// ===================================================================

UserInfo::UserInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, UserInfo_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobridge.UserInfo)
}
PROTOBUF_NDEBUG_INLINE UserInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::protobridge::UserInfo& from_msg)
      : _has_bits_{from._has_bits_},
        roles_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::protobridge::UserInfo,
              PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.roles_)>()
          , arena, from.roles_
        }
        ,
        username_(arena, from.username_),
        email_(arena, from.email_) {}

UserInfo::UserInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UserInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : Super_(arena, UserInfo_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : Super_(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UserInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, created_at_unix_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::created_at_unix_));

  // @@protoc_insertion_point(copy_constructor:protobridge.UserInfo)
}
PROTOBUF_NDEBUG_INLINE UserInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : roles_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::protobridge::UserInfo,
            PROTOBUF_FIELD_OFFSET(::protobridge::UserInfo, _impl_.roles_)>()
         }
        ,
        username_(arena),
        email_(arena) {}

inline void UserInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, created_at_unix_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::created_at_unix_));
}
UserInfo::~UserInfo() {
  // @@protoc_insertion_point(destructor:protobridge.UserInfo)
  SharedDtor(*this);
}
inline void UserInfo::SharedDtor(MessageLite& self) {
  UserInfo& this_ = static_cast<UserInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.username_.Destroy();
  this_._impl_.email_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UserInfo_class_data_ =
        UserInfo::InternalGenerateClassData_(UserInfo_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UserInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UserInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UserInfo_class_data_.tc_table);
  return UserInfo_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UserInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UserInfo_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&UserInfo_globals_));
  return UserInfo_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const UserInfo::ParseTableT_
    UserInfo::_table_ =
        UserInfo::InternalGenerateParseTable_(UserInfo_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void UserInfo::Clear() {
  auto& this_ [[maybe_unused]] = *this;
  // @@protoc_insertion_point(message_clear_start:protobridge.UserInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.roles_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      this_._impl_.username_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      this_._impl_.email_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000078U)) {
    ::memset(&this_._impl_.id_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&this_._impl_.created_at_unix_) -
                 reinterpret_cast<char*>(&this_._impl_.id_)) +
                 sizeof(_impl_.created_at_unix_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UserInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UserInfo& this_ = static_cast<const UserInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UserInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UserInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:protobridge.UserInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_id(), target);
    }
  }

  // string username = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_username().empty()) {
      const ::std::string& _s = this_._internal_username();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobridge.UserInfo.username");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string email = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_email().empty()) {
      const ::std::string& _s = this_._internal_email();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobridge.UserInfo.email");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // int32 age = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_age() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_age(), target);
    }
  }

  // bool is_active = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_is_active() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_is_active(), target);
    }
  }

  // int64 created_at_unix = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_created_at_unix() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<6>(
              stream, this_._internal_created_at_unix(), target);
    }
  }

  // repeated string roles = 7;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_roles_size(); i < n; ++i) {
      const auto& s = this_._internal_roles().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "protobridge.UserInfo.roles");
      target = stream->WriteString(7, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobridge.UserInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UserInfo::ByteSizeLong(const MessageLite& base) {
  const UserInfo& this_ = static_cast<const UserInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UserInfo::ByteSizeLong() const {
  const UserInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:protobridge.UserInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits [[maybe_unused]] = 0;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // repeated string roles = 7;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_roles().size());
      for (int i = 0, n = this_._internal_roles().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_roles().Get(i));
      }
    }
    // string username = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_username().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_username());
      }
    }
    // string email = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_email().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_email());
      }
    }
    // uint64 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_id());
      }
    }
    // int32 age = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_age() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_age());
      }
    }
    // bool is_active = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_is_active() != 0) {
        total_size += 2;
      }
    }
    // int64 created_at_unix = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_created_at_unix() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_created_at_unix());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UserInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<UserInfo*>(&to_msg);
  auto& from = static_cast<const UserInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:protobridge.UserInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_roles()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_roles());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_username().empty()) {
        _this->_internal_set_username(from._internal_username());
      } else {
        if (_this->_impl_.username_.IsDefault()) {
          _this->_internal_set_username("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_email().empty()) {
        _this->_internal_set_email(from._internal_email());
      } else {
        if (_this->_impl_.email_.IsDefault()) {
          _this->_internal_set_email("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_id() != 0) {
        _this->_impl_.id_ = from._impl_.id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_age() != 0) {
        _this->_impl_.age_ = from._impl_.age_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_is_active() != 0) {
        _this->_impl_.is_active_ = from._impl_.is_active_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_created_at_unix() != 0) {
        _this->_impl_.created_at_unix_ = from._impl_.created_at_unix_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UserInfo::CopyFrom(const UserInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:protobridge.UserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserInfo::InternalSwap(UserInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.roles_.InternalSwap(&other->_impl_.roles_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.email_, &other->_impl_.email_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.created_at_unix_)
      + sizeof(UserInfo::_impl_.created_at_unix_)
      - PROTOBUF_FIELD_OFFSET(UserInfo, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata UserInfo::GetMetadata() const {
  return Super_::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobridge
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fuser_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
